delete from test_one 
delete from test_one WHERE non_index<=1
delete from test_one WHERE pk<=1
delete from test_one WHERE sk<=1
delete from test_one WHERE vindex<=1
delete from test_one WHERE sec_index<=1
delete from test_one WHERE non_index=1
delete from test_one WHERE pk=1
delete from test_one WHERE sk=1
delete from test_one WHERE vindex=1
delete from test_one WHERE sec_index=1
delete from test_one WHERE non_index<=1 ORDER BY non_index
delete test_one, test_two from test_one inner join test_two WHERE 1=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.non_index<=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.pk<=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.sk<=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.vindex<=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.sec_index<=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.non_index=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.pk=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.sk=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.vindex=1
delete test_one, test_two from test_one inner join test_two WHERE test_one.sec_index=1
delete from test_one,test_two USING test_one inner join test_two WHERE 1=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.non_index<=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.pk<=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.sk<=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.vindex<=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.sec_index<=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.non_index=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.pk=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.sk=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.vindex=1
delete from test_one,test_two USING test_one inner join test_two WHERE test_one.sec_index=1
delete from test_one WHERE non_index<=1 ORDER BY non_index